version: '3.3'
services:
  web:
    container_name: "jfl-api"
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=5000
    environment:
      - "TZ=Europe/Paris"
    restart: on-failure
    ports:
      - "5000:5000"
    volumes:
      - ./test/repo:/root/repo

volumes:
  repo: