version: '3.3'
services:
  web:
    container_name: "jfl-api"
    image: dragonir/jfl-api
    # build:
    #   context: .
    #   dockerfile: dockerfile
    environment:
      TZ: Europe/Paris
      TOKEN_FILE: /run/secrets/jfl-api-token
    depends_on:
      - db
    secrets:
      - jfl-api-token
    restart: on-failure
    ports:
      - "5000:5000"
    volumes:
      - ./test/repo:/app/repo
    healthcheck:
      test: "curl -f http://localhost:5000/health || exit 1"
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
    
secrets:
  jfl-api-token:
    file: ./secrets/jfl-api-token.txt

volumes:
  repo:
  db: